spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://localhost:3306/saverfwd
    username: root
    password: Navneet@1math
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true

  redis:
    host: localhost
    port: 6379

server:
  port: 8000

jwt:
  secret: s-afalfnafpqpfnqpcnqcqpkcqmcmysecret-key